### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by n7s** [sile-typesetter/fontproof#28]
SU.utf8char() was deprecated in SILE v0.11.0. Please use luautf8.char() instead.

**Comment by alerque** [comment]
I also unable to see any usages of this left either in fontproof or SILE itself. I'd be happy to help fix anything that needs it but this seems to be a non-issue. Unless maybe the problem is in SILE itself not being the latest release? I seem to recall this still needs updating to v0.12.0, perhaps the error is being thrown relative to an old version of SILE being used.

**Comment by n7s** [comment]
Sorry, my mistake, it turns out these warnings are coming from fontproof but from the classes shipping [inside smith](https://github.com/silnrsi/smith/tree/master/smithlib/classes). I can confirm we are running the lastest SILE and fontproof versions. I got confused looking through the logs of our font builds and mixed up the results.

**Comment by alerque** [comment]
No problem, glad it got tracked down. If you need help porting deprecated bits to new APIs please feel free to ask. I typically test deprecations on my own past projects but that doesn't always catch edge cases where the replacement isn't clear.
