### ISSUE TITLE
Help with fontproof API changes and long-term maintainership

### ISSUE THREAD

**Issue by n7s** [sile-typesetter/fontproof#37]
Hi Caleb,

I've been trying to get fontproof to follow the recent API changes but I'm now stuck with how new packages are designed to work. 
Victor - the original author - isn't able to dedicate time to this, so we think it would be great if you could take a look and if fontproof just became one of the packages/classes who are part of sile rather than a separate project. You are most definitely the best person to keep up with the API changes so fontproof can continue working as expected. Thank you for considering it. 

Other fontproof related issues: https://github.com/sile-typesetter/sile/issues/722 and https://github.com/sile-typesetter/sile/issues/797 

Thanks!

**Comment by alerque** [comment]
I have it on my todolist already to port this to a new module format and ditch the requirement to be it's own executable with monkey-patched paths. I specifically designed some of the new APIs with this use case in mind  so that things like the SIL files included as templates could be referenced when installed as part of a LuaRocks module. Sorry I haven't done it yet...

**Comment by jvgaultney** [comment]
Many thanks, Caleb. After the port is done I hope to resume making small enhancements here and there..

**Comment by alerque** [comment]
Thanks for the ping. This *had* fallen off my radar again.

On a personal level we've had a bit of a rough patch. My daughter started having seizures like crazy at the end of last year and eventually was diagnosed with TSC. That's taken a huge bite out of both my time and ability to focus with the time I do have. We're starting to adjust and get some semblance of routine back.

This isn't really a big task, so I just sat down and hacked on it a bit. I got it as far as a proof-of-concept that renders a template again. The new layout is to have `luarocks install` take care of placing both the SILE class and package that will be used, as well as some templates and a script wrapper used as an entry point. The script `fontproof` is just a shorthand for passing calling `sile` with specific arguments, specifically: some variables from the CLI to the class to pick a font to test, pick one of the predefined template docs to render with, and output to a specific file. The `--help` argument should clarify a bit. Optionally the class provides all the commands no you could provide your own template instead of using one of the builtins.

Does that all sound conceptually right?

It's a little awkward to test in dev form because of Lua path handling, but `make install` should provide a **local** dev install that can be run from `./lua_modules/bin/fontproof`.

**Comment by alerque** [comment]
See https://github.com/sile-typesetter/fontproof/pull/38#issuecomment-1483920188 for how to start testing.

**Comment by n7s** [comment]
So sorry to hear about your daughter's health issues, hoping and praying she can get better soon. I understand the joys and challenges of parenting and how other everything else just has to wait! Thanks for all the work on this, I am doing some more testing. Thanks!

**Comment by jvgaultney** [comment]
Many thanks for your work on this!
